
replicaCount: 1

image:
  repository: peterjreg.azurecr.io/semver
  tag: 0.1.2
  pullPolicy: Always
  imagePullSecret: peterjregistry

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
  path: /
  hosts:
    - bump.semver.xyz
    - www.bump.semver.xyz
  tls: 
   - secretName: tls-semver-svc-secret
     hosts:
       - "bump.semver.xyz"
       - "www.bump.semver.xyz"